api/urls.py
from django.urls import path
from api.views import *

urlpatterns = [
    # Auth
    path('register/', RegisterView.as_view(), name='api_register'),
    path('login/', LoginView.as_view(), name='api_login'),
    path('logout/', LogoutView.as_view(), name='api_logout'),
    # Users
    path('users/', UsersView.as_view(), name='api_users'),
    # Resumes
    path('resumes/', ResumesView.as_view(), name='api_resumes'),
    path('resume/', ResumeView.as_view(), name='api_resume'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('app.urls')),
    path('api/', include('api.urls')),
    path('admin/', admin.site.urls),
]

app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from app.types import LanguageChoices


@receiver(post_save, sender=User)
def user_post_save(sender, instance, created, **kwargs):
    # Создаём резюме сразу после создания нового объекта
    if created:
        Resume(user=instance).save()


class Resume(models.Model):
    user = models.OneToOneField(to=User, on_delete=models.CASCADE, related_name='resume', verbose_name='Пользователь',
                                null=True)
    name = models.CharField(max_length=64, verbose_name='ФИО кандидата', blank=True, default='')
    hobbies = models.CharField(max_length=256, verbose_name='Увлечения', blank=True, default='')

    class Meta:
        db_table = 'resumes'
        verbose_name = 'Резюме'
        verbose_name_plural = 'Резюме'

    def __str__(self):
        return self.name


class Skill(models.Model):
    resume = models.ForeignKey(to=Resume, on_delete=models.SET_NULL, related_name='skills', verbose_name='Резюме',
                               null=True)
    value = models.CharField(max_length=32, verbose_name='Навык')

    class Meta:
        db_table = 'skills'
        verbose_name = 'Навык'
        verbose_name_plural = 'Навыки'

    def __str__(self):
        return self.value


class Language(models.Model):
    resume = models.ForeignKey(to=Resume, on_delete=models.SET_NULL, related_name='languages', verbose_name='Резюме',
                               null=True)
    language = models.CharField(max_length=2, choices=LanguageChoices.choices, verbose_name='Язык')

    class Meta:
        db_table = 'languages'
        verbose_name = 'Язык'
        verbose_name_plural = 'Языки'

app/templates/base.html
<!DOCTYPE html><html lang="en">{% block head %}<head>    <meta charset="utf-8" />    <title>{% block title %}Добро пожаловать!{% endblock %}</title>    <!-- FONT -->    <link rel="preconnect" href="https://fonts.gstatic.com">    <link href="https://fonts.googleapis.com/css2?family=Ubuntu&display=swap" rel="stylesheet">    <style type="text/css">* {font-family: 'Ubuntu', sans-serif !important}</style>    <!-- JS -->    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js""></script>    <!-- BOOTSTRAP -->    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"></script>    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>    <!-- CSS -->    <link href="/static/css/style.css" rel="stylesheet" type="text/css" />    <!-- TOASTIFY -->    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/toastify-js/src/toastify.min.css">    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/toastify-js"></script></head>{% endblock %}<body>    <!-- Preloader: START -->    <div class="preloader">        <div class="preloader__row">            <div class="preloader__item"></div>            <div class="preloader__item"></div>        </div>    </div>    <script>        $(window).on('load', function () {            $('.preloader').fadeOut().end().delay(400).fadeOut('slow');        });    </script>    <!-- Preloader: END -->    {% block content_base %}    {% endblock %}    <script src="/static/js/script.js"></script></body></html>

app/templates/header.html
{% extends "base.html" %}{% block content_base %}<nav class="navbar fixed-top navbar-expand-lg" id="header">    <div class="collapse navbar-collapse" id="navbarSupportedContent">        <ul class="navbar-nav mr-auto">            <li class="nav-item active">                <a href="{% url 'index' %}" class="nav-link"><i class="bi bi-house"></i> На главную</a>            </li>            {% if not user.is_authenticated %}                <li class="nav-item active">                    <a href="#" class="nav-link" onclick="$('#loginModal').modal('show')"><i class="bi bi-box-arrow-in-right"></i>                        Вход</a>                </li>                <li class="nav-item active">                    <a href="#" class="nav-link" onclick="$('#regModal').modal('show')"><i class="bi bi-person"></i> Регистрация</a>                </li>            {% else %}                <li class="nav-item">                    <a class="nav-link" href="{% url 'resume' %}"><i class="bi bi-person-circle"></i> Мой профиль</a>                </li>                <li class="nav-item">                    <a class="nav-link" href="{% url 'api_logout' %}"><i class="bi bi-door-closed"></i> Выход</a>                </li>            {% endif %}        </ul>    </div></nav>{% block content %}{% endblock %}{% include "popup.html" %}{% endblock %}

app/templates/index.html
{% extends "header.html" %}{% block content %}<section id="home">    <div id="cards">        {% for resume in resumes %}        <div class="card">            <div class="card-body">                <h3 class="card-title"><i class="bi bi-person"></i> {{ resume.name }}</h3>                <h6 class="card-subtitle mb-2 text-muted skills">                    {% for skill in resume.skills.all %}                        <span class="badge badge-secondary">{{ skill.value }}</span>                    {% endfor %}                </h6>                <p class="card-text">                    <b>Языки</b>:                    {% for lang in resume.languages.all %}                        {{ lang.get_language_display }}{% if not forloop.revcounter0 == 0 %}, {% endif %}                    {% endfor %}                    <br>                    <b>Увлечения</b>: {{ resume.hobbies }}                </p>            </div>        </div>        {% endfor %}    </div></section>{% endblock %}